# We simulate capistrano's behaviour.

- name: Create the "{{ linuxfr_environment }}" directory
  file: path={{ linuxfr_home }}/{{ linuxfr_environment }} state=directory

- name: Link the git repository to 'current'
  file: src={{ linuxfr_home }}/source dest={{ linuxfr_home }}/{{ linuxfr_environment }}/current state=link
