# We simulate capistrano's behaviour.

- name: Create the "development" directory
  file: path={{ linuxfr_home }}/development state=directory

- name: Link the git repository to 'current'
  file: src={{ linuxfr_home }}/source dest={{ linuxfr_home }}/development/current state=link
