- name: Clone the LinuxFR repository
  git: repo={{ linuxfr_repository['url'] }} version={{ linuxfr_repository['branch'] }} dest={{ linuxfr_home }}/src/linuxfr.org

- name: Configure the Rails apps's database
  copy: src=linuxfr/database.yml dest={{ linuxfr_home }}/src/linuxfr.org/config/database.yml

- name: Configure the Rails apps's secrets
  copy: src=linuxfr/secret.yml dest={{ linuxfr_home }}/src/linuxfr.org/config/secret.yml

- name: Install the Rails app using Bundler
  command: bundle install chdir={{ linuxfr_home }}/src/linuxfr.org

- name: Install the ElasticSearch init script
  copy: src=init.d/elasticsearch dest=/etc/init.d/elasticsearch mode=0755

# Stinky workaround for https://github.com/AF83/desi/issues/25
- name: Setup ElasticSearch
  command: desi install {{ elasticsearch_version }} creates=/root/elasticsearch/elasticsearch-{{ elasticsearch_version }}
  notify:
    - restart elasticsearch

- name: Ensure ElasticSearch is enabled and started
  service: name=elasticsearch state=started enabled=yes

- name: Check if the database already exists
  command: rake db:version chdir={{ linuxfr_home }}/src/linuxfr.org
  ignore_errors: True
  register: db_version

- name: Setup the database
  command: rake db:setup chdir={{ linuxfr_home }}/src/linuxfr.org
  when: db_version|failed

- name: Migrate the database
  command: rake db:migrate chdir={{ linuxfr_home }}/src/linuxfr.org
  when: db_version|success

- name: Flush the Redis database
  command: redis-cli flushdb

# This doesn't work because  undefined method `tire' for #<Class:0x00000005cdedf8> (NoMethodError)
#- name: Initialize indexes
#  command: ./script/rails r '[Diary, News, Page, Poll, Post, Tracker, WikiPage].each {|m| m.tire.index.refresh }'
#           chdir={{ linuxfr_home }}
