- name: Clone the LinuxFR repository
  git: repo=git://github.com/nono/linuxfr.org.git dest=/srv/sources/linuxfr.org

- name: Configure the Rails apps's database
  copy: src=linuxfr/database.yml dest=/srv/sources/linuxfr.org/config/database.yml

- name: Configure the Rails apps's secrets
  copy: src=linuxfr/secret.yml dest=/srv/sources/linuxfr.org/config/secret.yml

- name: Check PATH
  shell: echo $PATH
  environment:
    PATH: $PATH:{{ ruby_path }}

- name: Install the Rails app using Bundler
  command: bundle install chdir=/srv/sources/linuxfr.org
  environment:
    PATH: $PATH:{{ ruby_path }}

- name: Setup ElasticSearch
  command: desi install chdir=/srv/sources/linuxfr.org
  environment:
    PATH: $PATH:{{ ruby_path }}

- name: Setup the database
  command: rake db:setup chdir=/srv/sources/linuxfr.org
  environment:
    PATH: $PATH:{{ ruby_path }}

- name: Flush the Redis database
  command: redis-cli flushdb

# This doesn't work because  undefined method `tire' for #<Class:0x00000005cdedf8> (NoMethodError)
#- name: Initialize indexes
#  command: ./script/rails r '[Diary, News, Page, Poll, Post, Tracker, WikiPage].each {|m| m.tire.index.refresh }'
#           chdir=/srv/sources/linuxfr.org
#  environment:
#    PATH: $PATH:{{ ruby_path }}
