- name: Install MySQL
  apt: pkg={{ item }} state=installed
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Create the LinuxFR MySQL database
  mysql_db: name={{ item }} state=present
  with_items:
    - linuxfr_rails
    - linuxfr_test

- name: Create the LinuxFR MySQL user
  mysql_user: name={{ item }} password={{ item }} priv={{ item }}.*:ALL
  with_items:
    - linuxfr_rails
    - linuxfr_test
