- name: Install nginx
  apt: pkg=nginx-light state=installed

# We simulate capistrano's behaviour.

- name: Link the git repository to 'current'
  file: src=/data/{{ linuxfr_env }}/linuxfr/source dest=/data/{{ linuxfr_env }}/linuxfr/current state=link

# Wheezy doesn't create a /var/www anymore, as it is now recommended to put
# this kind of data inside /srv. We create it anyway to mimick the current
# installation process as advertised in the admin-linuxfr.org README file.

- name: Create the /var/www directory
  file: path=/var/www state=directory

- name: Link the linuxfr codebase into /var/www
  file: src=/data/{{ linuxfr_env }}/linuxfr dest=/var/www/linuxfr state=link
