- name: Install Ruby 2
  apt: pkg={{ item }} state=installed
  with_items:
    - ruby2.0

- name: Install Ruby Gems build dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - autoconf
    - automake
    - build-essential
    - curl
    - libc6-dev
    - libcurl4-openssl-dev
    - libmysql++-dev
    - libreadline6-dev
    - libssl-dev
    - libtool
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - libncurses5-dev
    - ruby2.0-dev
    - zlib1g-dev

- name: Create the ruby gem directory
  file: name={{ ruby_env['GEM_HOME'] }} state=directory

- name: Put the ruby-env file into the linuxfr home directory
  template: src=home/ruby-env.j2 dest={{ linuxfr_home }}/ruby-env

- name: Install Bundler gem
  gem: name=bundler state=latest user_install=no
  environment: ruby_env
