- name: Put the ruby-env file into the linuxfr home directory
  template: src=home/ruby-env.j2 dest={{ linuxfr_home }}/ruby-env

- name: Link the unicorn init script into place.
  file: src={{ linuxfr_home }}/src/admin/init.d/unicorn dest=/etc/init.d/unicorn state=link

- name: Ensure the directories used by unicorn exist.
  file: path={{ linuxfr_home }}/development/shared/{{ item }} state=directory owner=linuxfr group=linuxfr
  with_items:
    - pids
    - log

- name: Put the unicorn configuration into /etc/default/unicorn
  template: src=default/unicorn.j2 dest=/etc/default/unicorn
  notify:
    - restart unicorn
