linuxfr_env: dev
linuxfr_home: /data/{{ linuxfr_env }}/linuxfr

repositories:
  linuxfr:
    url: git://github.com/nono/linuxfr.org.git
    branch: master
  admin:
    url: git://github.com/nud/admin-linuxfr.org.git
    branch: master

img_repository:
  url: github.com/nono/img-LinuxFr.org

base_path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

go_env:
  GOPATH: "{{ linuxfr_home }}/go"
  GOROOT: "/usr/lib/go"
  PATH: "{{ linuxfr_home }}/go/bin:{{ base_path }}"
