linuxfr_user: linuxfr
linuxfr_home: /data/dev/linuxfr
linuxfr_environment: development

linuxfr_repository:
  url: git://github.com/nono/linuxfr.org.git
  branch: master

admin_repository:
  url: git://github.com/nud/admin-linuxfr.org.git
  branch: master

img_repository:
  url: github.com/nono/img-LinuxFr.org

base_path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ruby_env:
  RAILS_ENV: development
  GEM_HOME: "{{ linuxfr_home }}/gem"
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  PATH: "{{ linuxfr_home }}/gem/bin:{{ base_path }}"

go_env:
  GOPATH: "{{ linuxfr_home }}/go"
  GOROOT: "/usr/lib/go"
  PATH: "{{ linuxfr_home }}/go/bin:{{ base_path }}"

elasticsearch_version: 1.0.1
