- name: Install python-apt
  raw: sh -c 'test -d /usr/share/pyshared/apt || apt-get install -y python-apt'

- name: Update APT cache
  apt: update_cache=yes

- name: Install ansible modules dependencies
  apt: pkg=python-pycurl state=installed

- name: Install generally useful packages.
  apt: pkg={{ item }} state=installed
  with_items:
    - bash-completion
    - git
    - tmux
    - vim
    - w3m
