- name: Update APT cache
  apt: update_cache=yes

- name: Install python-apt
  command: apt-get install -y python-apt creates=/usr/share/pyshared/apt

- name: Install ansible modules dependencies
  apt: pkg=python-pycurl state=installed

- name: Install generally useful packages.
  apt: pkg={{ item }} state=installed
  with_items:
    - bash-completion
    - git
    - tmux
    - vim
    - w3m
