- name: Update APT cache
  apt: update_cache=yes

- name: Install python-apt
  command: apt-get install -y python-apt creates=/usr/share/pyshared/apt

- name: Create sources directory for downloads.
  file: state=directory path=/srv/sources

- name: Install generally useful packages.
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - git
