- name: Create the LinuxFR user
  user: name={{ linuxfr_user }} home={{ linuxfr_home }} state=present

- name: Create the cache and logs directories
  file: path={{ item }} state=directory owner={{ linuxfr_user }} group={{ linuxfr_user }}
  with_items:
    - "{{ linuxfr_home }}/logs"
    - "{{ linuxfr_home }}/cache"
